### PR TITLE
SSL Checker

### PR DESCRIPTION
**Pull request by subhamagrawal7**
This checks if the website uses an SSL Certificate using the https package
This is to address the issue Check if the website using SSL #6

### CODE REVIEW

**Comment by subhamagrawal7** [comment]
@sam0hack please review and tell if any necessary changes need to be done

**Comment by sam0hack** [comment]
I like the idea of using that package but can you add this in the main program so when we get results  It would tell us if the website has SSL.

**Comment by subhamagrawal7** [comment]
Ok sure I would add in the main program directly in cache_checker file

**Comment by sam0hack** [comment]
thanks @subhamagrawal7

**Comment by subhamagrawal7** [comment]
I have added the code into main program for the SSL checker. please check.

**Comment by subhamagrawal7** [comment]
@sam0hack please do tell if any changes are required.

**Comment by sam0hack** [comment]
@subhamagrawal7 this branch has conflicts

**Comment by subhamagrawal7** [comment]
Is it fine now?

**Comment by sam0hack** [comment]
@all-contributors please add @subhamagrawal7  for tool test and code

**Comment by subhamagrawal7** [comment]
@sam0hack thank you so much got to learn a lot!!

**Pull request merged**
