### PR TITLE
added option to get server details from response.headers

### PR DESCRIPTION
**Pull request by ogheneovo12**
the user only need to pass the optional flag `--server`  || `-s`  to the cli, to get server details

### CODE REVIEW

**Comment by sam0hack** [comment]
Hi @ogheneovo12 this merge has conflicts

**Comment by ogheneovo12** [comment]
yeah am fixing it

**Comment by sam0hack** [comment]
again! too many changes coming on our way I'll hold other changes this time so you can make this commit

**Comment by ogheneovo12** [comment]
yeah am trying to decide what better way to accept commands from cli, so that user will not pass invalid URL to script, or let the flag be passed as url

**Comment by ogheneovo12** [comment]
i intended to use the URL constructor to validate the URL first, but I realized that it sees URL without a scheme as invalid eg "www.google.com"

**Comment by ogheneovo12** [comment]
@sam0hack i noticed a little issue with the code for getting site security details

**Comment by sam0hack** [comment]
@all-contributors please add @ogheneovo12  for tool test and code

**Pull request merged**
